Resources:
  MyInstance:
   Type: AWS::EC2::Instance
   Properties:
    InstanceType: t2.micro
    ImageId: ami-07761f3ae34c4478d
    Tags:
     - Key: "Name"
       Value: !Join 
       - " "
       - - "My Instance in"
         - !Ref AWS::Region